### ISSUE TITLE
Patch will not handle file names with "__" common python file example __init__.py 

### ISSUE THREAD

**Issue by chgray54** [willnx/iiqtools#14]
See: https://github.com/willnx/iiqtools/blob/fcf4979424d98ac2e552dbe16cf5c53a97259895/iiqtools/iiq_patch.py#L334

**Comment by willnx** [comment]
Great catch! I'll get busy fixing that.

![doh](http://i0.kym-cdn.com/photos/images/original/000/925/410/4cc.jpg)
