### ISSUE TITLE
struct error export too large.

### ISSUE THREAD

**Issue by sk3ndall** [willnx/iiqtools#25]
I am getting errors trying to convert to a zip.  Looks like the export was too large.
```
[administrator@vcmcinsightiq tmp]$ /opt/rh/python27/root/usr/bin/iiqtools_tar_to_zip -s insightiq_export_1522783418.tar.gz -o /mnt/10.193.6.113/ifs/data/IIQ2/
2018-04-04 20:13:37,625 - INFO - Converting insightiq_export_1522783418.tar.gz to zip format
2018-04-04 20:34:32,536 - INFO - InsightIQ datastore tar export contained 2 files
2018-04-04 20:34:32,536 - INFO - Converting insightiq_export_1522783418/vcmc-12kisilon_00151b00007a2716ce4a1504000067458b6b_config.json
2018-04-04 20:34:32,560 - INFO - Converting insightiq_export_1522783418/vcmc-12kisilon_00151b00007a2716ce4a1504000067458b6b.dump
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/bin/iiqtools_tar_to_zip", line 11, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/iiqtools/iiqtools_tar_to_zip.py", line 192, in main
    zip_export.writebuffered(filename=filename, file_handle=file_handle)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/iiqtools/iiqtools_tar_to_zip.py", line 80, in writebuffered
    self.fp.write(struct.pack("<LLL", zinfo.CRC, zinfo.compress_size, zinfo.file_size))
struct.error: 'L' format requires 0 <= number <= 4294967295
```

**Comment by sk3ndall** [comment]
Looks like a known python bug https://bugs.python.org/issue9720. If there is no work around on this side may have to look at patching the zipfile.py as suggested in that bug.

**Comment by willnx** [comment]
Thanks for filing this bug! I'll take a look at a workaround/patch. In the mean time, if you have the disk space, you should be able to just untar the old export, then zip up the resulting directory. All you really have to do is change the extentions from `.tar.gz` to `.zip`; the rest of the naming pattern is the same.

**Comment by willnx** [comment]
Looks like the issue isn't the size of the `.tar.gz` file; it's with the size of a `.dump` file that's within the tar.
Full disclosure, I'm on vacation/holiday for the next week, so it'll be a little bit before I push an update. Hey @sk3ndall, if you feel like issuing a PR for this I'll take the time to look at it while here in Hawaii.

**Comment by sk3ndall** [comment]
Enjoy your vacation.  I’ll try the untar and manually zip method here shortly.

Thanks,
Steven Kendall
[signature_2032560059]
CSE Systems Creation
C- 214-683-4177
O-972-578-6820
Steven.Kendall@verizon.com

**Comment by sk3ndall** [comment]
I extracted it.  The dumpfile is +100GB, so yeah way past that limit.  I am going to manually zip now and try.

Thanks,
Steven Kendall
[signature_1109656831]
CSE Systems Creation
C- 214-683-4177
O-972-578-6820
Steven.Kendall@verizon.com

**Comment by willnx** [comment]
Looks like a fix might be pretty simple. 

After reading up a bit on the [struct](
https://docs.python.org/2/library/struct.html#format-characters) module, I might be able to just replace this line:
https://github.com/willnx/iiqtools/blob/master/iiqtools/iiqtools_tar_to_zip.py#L80
```
        self.fp.write(struct.pack("<LLL", zinfo.CRC, zinfo.compress_size, zinfo.file_size))
```
With something like:
```
        self.fp.write(struct.pack("<LQQ", zinfo.CRC, zinfo.compress_size, zinfo.file_size))
```
Which would push the file size limit up to a 64bit unsigned integer, so roughly 18 Exabytes; god help the poor sole with that much IIQ data ;)

Testing this will have to wait until I'm back in the office; not sure if there will be a weird side effect of this change, and I don't have the resources on my laptop to poke this while on vacation.
