### ISSUE TITLE
Allow iiqtools_cluster_backup to backup all monitored clusters

### ISSUE THREAD

**Issue by berniecase** [willnx/iiqtools#32]
Pretty self-explanatory. Right now you have to specify a cluster, but it would be nice if there was an --all-clusters option that'd just backup all monitored clusters, one at a time (or maybe simultaneous?)

**Comment by berniecase** [comment]
And yes, you can specify --clusters <name> <name> <name> but that goes into one output zip file. So as I look at this, this goes more with Issue #33.

**Comment by berniecase** [comment]
Cool! I just wouldn’t want to put all cluster backups in one file. Separate files for each cluster would be more manageable for the customer I’m thinking of.

**Comment by willnx** [comment]
> ...would be more manageable for the customer I’m thinking of.

Well tell them to login to Github and file the feature request themselves :P

**Comment by willnx** [comment]
I just merged #35 to address this issue. I'll have a new IIQTools RPM posted to the repo within the hour.
